### ISSUE TITLE
Playback Failed

### ISSUE THREAD

**Issue by lamp5** [smedic/Android-YouTube-Background-Player#20]
Hi. I want to report that app not working. After select my google account, nothing shown in tabs, after search anything, when i want to start playing video, only message shown "Playback Failed". It will be great to fix this errors. 
Best regards

**Comment by smedic** [comment]
I fixed it, please check if works

**Comment by jsmith2194** [comment]
Hi still the same issue it says video playback failed . Also could you not remove video thumbnail and use Spotify api to get album covers

**Comment by smedic** [comment]
Why would I do that?
You are free to add that and make PR.

**Comment by smedic** [comment]
Issue with playback is related to a small library that I use for extracting RTSP link from YT page (with video id). That's the way how I get URLs for playback.

**Comment by harshit-joshi** [comment]
Still not working

**Comment by tristanneumann1** [comment]
Still an issue

**Comment by boredomdenied** [comment]
yea this is still not working.

**Comment by smedic** [comment]
This is an open source project, so please fill to contribute. It's not a production ready application tested on wide range of devices.
I tested on S7 and S8 and it works good. On Huawei P9 Lite I have seen some playback failures.
If you have issue, leave more information about device and Android version, so maybe I/someone could fix that in the future.

**Comment by saurabhpal007** [comment]
Not working in Android Nougat

**Comment by WormyGels** [comment]
Playback seems to work for videos that are not music. Google knows whether a video is music or not, and disallow the popup window with music on their own app.

**Comment by harut2005** [comment]
I don't understand what exactly you mean with the popup window. 
And I don't see any clear correlation between music videos and the videos that have playback issues with this app. 

@smedic do you have any ideas on how to fix this? 
Could you describe how you fixed it last time, perhaps someone of us could could possibly handle it, if you are too busy at the moment.

**Comment by WormyGels** [comment]
@harut2005 The official YouTube app for Android has a popup window so you can watch a video while doing other things on the phone. They disable this popup window if a video has certain special copyrights (detected to be music).

From my admittedly limited testing it seems every video that fails playback with this app is also disallowed in the popup window on the official YouTube app. Something to look into.

**Comment by smedic** [comment]
@harut2005 @WormyGels I use a library for extracting RTSP link from youtube page 
https://github.com/HaarigerHarald/android-youtubeExtractor
As you can see, YouTube constantly changes things so that app is not capable of extracting links from YT page. I must check what changes developer has added, and update the library.

You know already that YT forbids logic that I used here, so they change stuff to disable workarounds like this. I ll take a look these days, I promise. 

Thanks for a constructive chat, I am glad you find this usable :)

**Comment by doctorbhatti** [comment]
Hi, 
I am a beginner in the field of development, I tried your project and it is something worth of a gem.
But as others have mentioned above, I am also facing the same issue. 
I just want to ask a silly question and that is 
"Is it possible to feed the raw URL to mediaplayer as data source instead of getting URL in two chunks i.e a standard https://youtube.com/blahblahblah and video id separately?"
By the way thanks for the project.
